apiVersion: argoproj.io/v1alpha1  
kind: Application  
metadata:  
  name: my-k8s-app
  namespace: argocd  
spec:  
  project: default  
  source:  
    repoURL: https://github.com/nainit-virtueinfo/my-k8s-app.git
    targetRevision: HEAD  
    path: application.yaml  
  destination:  
    server: https://kubernetes.default.svc  
    namespace: my-k8s-app
  syncPolicy:  
    automated:  
      prune: true  
      selfHeal: true  
    syncOptions:  
      - CreateNamespace=true
